// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt-vvMRCYqMxZEtjZPIsNNuC7AKcLSKsg',
    appId: '1:291089351662:web:8f9e830e536532803904ff',
    messagingSenderId: '291089351662',
    projectId: 'the-track-and-field-network',
    authDomain: 'the-track-and-field-network.firebaseapp.com',
    storageBucket: 'the-track-and-field-network.firebasestorage.app',
    measurementId: 'G-Z4LJ142TV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt-vvMRCYqMxZEtjZPIsNNuC7AKcLSKsg',
    appId: '1:291089351662:web:4f8f176ac57b56dc3904ff',
    messagingSenderId: '291089351662',
    projectId: 'the-track-and-field-network',
    authDomain: 'the-track-and-field-network.firebaseapp.com',
    storageBucket: 'the-track-and-field-network.firebasestorage.app',
    measurementId: 'G-9PQE1EDCHT',
  );

}